
   
name: 'Refresh AliCloud CDN Cache'
description: 'Refresh AliCloud CDN Cache'
inputs:
  access_key_id:
    description: 'AliCloud Access ID'
    required: true
  access_key_secret:
    description: 'AliCloud Access Secret'
    required: true
  file_paths:
    description: 'File Path'
    required: true

outputs:
  result:
    description: 'Result'
    value: '{}'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        pip3 install alibabacloud_cdn20180510==1.0.7
        python3 scripts/refresh_cdn_cache.py ${{ inputs.access_key_id }} ${{ inputs.access_key_secret }} ${{ inputs.file_paths }}
