name: Test Action

on: 
  push:
    branches:
      - master

jobs:
  test-refresh:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: test refresh cdn cache
      uses: ./
      with:
        access_key_id: ${{ secrets.ALI_ACCESS_KEY_ID }}
        access_key_secret: ${{ secrets.ALI_ACCESS_KEY_SECRET }}
        file_paths:
          https://api.codming.com/
          https://img.codming.com/
          https://api.codming.com/test.txt
          https://img.codming.com/favicon.ico
